stages:
  - test

image: hashicorp/terraform:0.12.24

terraform_version:
  stage: test
  script:
    - echo "This job tests something. It will only run when all jobs in the"
    - echo "build stage are complete."
    # - terraform version